"""add main_crop to plots

Revision ID: 317a392b749f
Revises: 
Create Date: 2026-09-14 20:20:47.486252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '317a392b749f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "plots",
        sa.Column(
            "soil_status",
            sa.String(length=10),
            nullable=False,
            server_default="unknown",
        ),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plots', 'soil_status')
    op.drop_column('plots', 'main_crop')
    # ### end Alembic commands ###
